# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Základní pravidla 3.1'
copyright = '2020-2023'
author = ''


# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinxcontrib.plantuml'
    ]


templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'cs'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)
html_css_files = [
    'css/custom.css',
]

# Type of output image for HTML renderer. (default: 'png')
plantuml_output_format = 'svg'

# Type of output image for LaTeX renderer. (default: 'png')
# Because embedded png looks pretty bad, it is recommended to choose pdf for pdflatex or eps for platex.
plantuml_latex_output_format = 'pdf'
# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
	# The paper size ('letterpaper' or 'a4paper').
	'papersize': 'a4paper',	
	# The font size ('10pt', '11pt' or '12pt').
    'pointsize': '11pt',
    # Additional stuff for the LaTeX preamble.
    #'preamble': r'''\usepackage{longtable}''',
    'preamble': r'''\usepackage{longtable}
% --- Aggressive Float Placement Settings ---
% Allow floats to take up 95% of a page (default is often 70%)
\renewcommand{\textfraction}{0.05} 
% Allow the entire page to be a float page (default is often 90%)
\renewcommand{\floatpagefraction}{0.99} 
% Allow floats to fill up 99% of the top or bottom of a page
\renewcommand{\topfraction}{0.99}
\renewcommand{\bottomfraction}{0.99}
% Allow more than the default 2 floats at the top/bottom
\setcounter{topnumber}{4} 
\setcounter{bottomnumber}{4} 
% --- End Float Settings ---
''',
	# Latex figure (float) alignment
	#'figure_align': 'htbp',
   # https://github.com/sphinx-doc/sphinx/issues/10347
   'fontpkg': r'''\setmainfont{FreeSerif}[
  UprightFont    = *,
  ItalicFont     = *Italic,
  BoldFont       = *Bold,
  BoldItalicFont = *BoldItalic
]
\setsansfont{FreeSans}[
  UprightFont    = *,
  ItalicFont     = *Oblique,
  BoldFont       = *Bold,
  BoldItalicFont = *BoldOblique,
]
\setmonofont{FreeMono}[
  UprightFont    = *,
  ItalicFont     = *Oblique,
  BoldFont       = *Bold,
  BoldItalicFont = *BoldOblique,
]
''',
  # Disable all indexes
  'printindex': ''
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'zp.tex', 'Základní pravidla pro zpracování archiválií', 'MV ČR', 'manual'),
]

latex_engine = 'xelatex'
latex_show_urls = 'footnote'
latex_use_latex_multicolumn = True


# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
latex_domain_indices = False
